### PR TITLE
libbpf-rs: program: Show AsFd in documentation

### PR DESCRIPTION
**Pull request by danobi**
Previously, AsFd trait was implemented on ProgramImpl. Since ProgramImpl is not exported, the trait implementation did not show up on docs.rs. You could still use it - but it wasn't obvious that it was available.

### CODE REVIEW

**Review by d-e-s-o — COMMENTED** [review]
I think there are a bunch of cases where stuff doesn't show up at all or doesn't show up correctly in the documentation, especially after the recent introduction of the `Mut` variants. Problem is, I think that more than anything these are issues with `rustdoc`. I opened one or two issues in the past about problems in that realm, but since they haven't gotten any traction I stopped filing.
The change is fine in principle, but I am somewhat reluctant to merge it: we are introducing unnecessary complexity/duplication just to work around what I'd think is a bug (though I'd be happy to be convince of the contrary). If we merge that, we should merge every other similar fix up. And I am not sure where to draw the line once more complex/ugly/<...> work arounds are necessary.
If you feel strongly about fixing this and you agree it's a bug with the doc rendering, here would be my suggestion: open an issue and then reference this issue in a TODO at the two `AsFd` impl sites as a reminder to dedup things once fixed upstream. Then I'd be much less reluctatnt to merge the change. What do you think?

**Comment by danobi** [comment]
Yeah fair enough. Let’s put a pin in this for now. I’ll see if I can hack rustdoc to make this properly work

**Comment by danobi** [comment]
Can you share some of the issues you opened?

**Comment by d-e-s-o** [comment]
The only one in that realm that I found with a quick search is https://github.com/rust-lang/rust/issues/116854

**Comment by danobi** [comment]
Alright, I think I found the "official" solution

**Pull request closed without merging**
