### PR TITLE
Fix skeleton generation for enum64 types

### PR DESCRIPTION
**Pull request by danielocfb**
Please see individual commits for descriptions.

### CODE REVIEW

**Comment by danielocfb** [comment]
Hm, I wonder if some of the test failures are due to low clang/llvm version...everything is working locally.

**Review by anakryiko — APPROVED** [review]
LGTM, as discussed, enum64 test problem is probably due to old Clang

**Comment by danielocfb** [comment]
> LGTM, as discussed, enum64 test problem is probably due to old Clang

Thanks! Will see if we can fix that tomorrow. Worst case we have to ignore the test in CI.

**Comment by etsal** [comment]
I can confirm this fixes the compilation problem. Thank you!

**Comment by danielocfb** [comment]
> I can confirm this fixes the compilation problem. Thank you!

Let me know in case you need a new release with this fix.

**Comment by etsal** [comment]
> > I can confirm this fixes the compilation problem. Thank you!
> 
> Let me know in case you need a new release with this fix.

Sorry for the late response. That would be great, thank you.

**Comment by danielocfb** [comment]
Okay, [`v0.25.0-beta.1`](https://crates.io/crates/libbpf-rs/0.25.0-beta.1) is out now.

**Pull request merged**
