### PR TITLE
libbpf-rs: Add support for USDT probes

### PR DESCRIPTION
**Pull request by ueno**
This adds a wrapper around bpf_program__attach_usdt introduced in libbpf-sys v1.0.0, which allows BPF programs to be attached to USDT probe points.

Signed-off-by: Daiki Ueno <dueno@redhat.com>

### CODE REVIEW

**Comment by ueno** [comment]
@danielocfb I have added a test using the [probe](https://crates.io/crates/probe) crate. It works locally but might need some adjustment to cope with older Rust toolchain without `asm!`.

**Review by danielocfb — CHANGES_REQUESTED** [review]
Your changes look great! Thanks for adding a test as well. I have one small request before we go ahead and merge, which is to please just bump our Rust version to use to `1.60` instead of making the test run conditionally (and drop the last commit altogether). Right now we are not overly concerned about the minimum Rust version we require and so it's fine to bump. [Here](https://github.com/libbpf/libbpf-rs/commit/838aca4afd9f5282a5fb433028e15c377cc2800c) is a commit showing the steps necessary.

**Comment by ueno** [comment]
@danielocfb thank you for the pointer; I have updated the minimum required version (it was actually 1.59.0 that inline assembly got supported) and dropped the conditional compilation code.

**Review by danielocfb — APPROVED** [review]
Looks great to me! Thanks again.

**Pull request merged**
