### PR TITLE
libbpf-rs, libbpf-cargo: Update to libbpf-sys v 1.1.0

### PR DESCRIPTION
**Pull request by mimullin-bbry**
Update both libbpf-rs and libbpf-cargo to version 1.1.0

Signed-off-by: Michael Mullin <mimullin@blackberry.com>

### CODE REVIEW

**Comment by mimullin-bbry** [comment]
The time crate now has a minimum requirement of version 1.60.  I believe that runqslower will fail for all builds once a cargo update is run.

Suggestion: update libbpf-rs/libbpf-cargo minimum requirement to 1.60.

**Comment by danielocfb** [comment]
Thanks for the pull request. Can you please remove all the unrelated updates from `Cargo.lock` and focus this one to only the `libbpf-sys` bump? Then, presumably, CI would pass as well.

**Comment by mimullin-bbry** [comment]
> Thanks for the pull request. Can you please remove all the unrelated updates from `Cargo.lock` and focus this one to only the `libbpf-sys` bump? Then, presumably, CI would pass as well.

Done.  BTW I just learned about "cargo update -p" which allows for updating a single package :)

**Comment by danielocfb** [comment]
> Done. BTW I just learned about "cargo update -p" which allows for updating a single package :)

Thank you!

**Pull request merged**
