### PR TITLE
maps: support batch delete

### PR DESCRIPTION
**Pull request by WeiZhang555**
Add new map function "delete_batch".

### CODE REVIEW

**Comment by WeiZhang555** [comment]
Since the purpose of `map_delete` is obvious, so the commit message is short, I could add more necessary descriptions if required.

Also, unit-tests is on the way, still struggling with it.

**Comment by danielocfb** [comment]
Hi @WeiZhang555 , thanks for the pull request. can you please add unit tests for this new functionality?

**Comment by WeiZhang555** [comment]
> Hi @WeiZhang555 , thanks for the pull request. can you please add unit tests for this new functionality?

Of course, I'm struggling with it :-)

**Comment by WeiZhang555** [comment]
@danielocfb UT is added, and it passed. Please take a look at it.

**Comment by danielocfb** [comment]
> @danielocfb UT is added, and it passed. Please take a look at it.

Thank you!

**Review by danielocfb — APPROVED** [review]
Looks good to me. I made a few minor changes and added a CHANGELOG entry. Will merge in a bit. Thanks!

**Comment by danielocfb** [comment]
> Looks good to me. I made a few minor changes and added a CHANGELOG entry. Will merge in a bit. Thanks!

Done.

**Comment by WeiZhang555** [comment]
@danielocfb Thank you! :-)

**Pull request closed without merging**
