### PR TITLE
libbpf-cargo: Strip DWARF information from generated object files

### PR DESCRIPTION
**Pull request by danielocfb**
Clang generated BPF object files may contain DWARF information that
references paths to temporary directories, for example. That ends up
rendering our generated skeleton unstable, as it potentially changes
between invocations [0]. That can be unfortunate if the skeleton is
meant to be checked into version control.
Andrii suggested [1] stripping said DWARF information by linking the
object file, which strips it as a side effect. This change does so.

[0] https://github.com/libbpf/libbpf-rs/issues/163
[1] https://github.com/libbpf/libbpf-rs/pull/169#issuecomment-1006074629

Closes: https://github.com/libbpf/libbpf-rs/issues/177
Signed-off-by: Daniel Müller <deso@posteo.net>

### CODE REVIEW

**Comment by danielocfb** [comment]
I verified that the added test failed beforehand.

**Comment by danielocfb** [comment]
Grml...unsure where the failure is coming from, off hand. Will take another look.

**Comment by danielocfb** [comment]
That being said, if there are comments on the approach feel free to post them.

**Comment by danielocfb** [comment]
> ---- test::test_skeleton_builder_deterministic stdout ----
> clang is version 14.0.0
> Building /tmp/.tmpJeIbmy/proj/src/bpf/prog.bpf.c
> thread 'test::test_skeleton_builder_deterministic' panicked at 'called `Result::unwrap()` on an `Err` value: Build("Failed to compile obj=/tmp/.tmpu1nEWg/prog.o with status=exit status: 1\n stdout=\n \n stderr=\n In file included from /tmp/.tmpJeIbmy/proj/src/bpf/prog.bpf.c:2:\nIn file included from /usr/include/linux/bpf.h:11:\n/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found\n#include <asm/types.h>\n         ^~~~~~~~~~~~~\n1 error generated.\n\n")', libbpf-cargo/src/test.rs:955:10

It appears as if the linux-headers package may be broken on Ubuntu? `/usr/include/linux/types.h` references `asm/types.h`, but that does not exist. What does exist is `/usr/include/asm-generic/types.h`. Both `/usr/include/linux/types.h` and `/usr/include/asm-generic/types.h` seem to be provided by the `linux-headers` package. There are other versions and variants of this virtual package available, but none seem to make a difference. Logically, it seems wrong for a header in a package to reference something outside of this package but not have that declared as an explicit dependency. Things work fine on my local system.
I also tried installing `linux-source` but that did not help.

I think it's probably not worth dealing with issues like that. So I think we should just make the test ignored. Then it won't be run by default but we can still do so on demand.

**Comment by danielocfb** [comment]
I ended up symlinking `asm/` to `asm-generic/` and it works. Still keeping the test as ignored, but explicitly overwriting that in CI now. So we should be all good.

Some links touching on the mess:
https://www.mail-archive.com/redhat-list%40redhat.com/msg49603.html
https://stackoverflow.com/questions/65591871/asm-vs-asm-generic-in-linux-headers-are-they-same
https://stackoverflow.com/questions/14795608/asm-errno-h-no-such-file-or-directory

**Comment by insearchoflosttime** [comment]
LGTM

**Pull request merged**
